run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: volcano-job-analyzer

  golint:
    min-confidence: 0.8

  gocyclo:
    min-complexity: 20

  maligned:
    suggest-new: true

  dupl:
    threshold: 200

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 240
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentedOutCode
      - hugeParam
      - rangeValCopy
      - paramTypeCombine
      - ifElseChain
      - unnamedResult

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK

  funlen:
    lines: 160
    statements: 120

  gocognit:
    min-complexity: 80

  nestif:
    min-complexity: 8

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - unparam

  disable:
    - maligned  # deprecated
    - exhaustivestruct  # too strict for this project
    - depguard
    - golint
    - gosec
    - goconst
    - gomnd
    - gocyclo
    - gocritic
    - dupl
    - funlen
    - lll
    - whitespace
    - gocognit
    - nestif
    - bodyclose
    - deadcode
    - dogsled
    - gochecknoinits
    - goprintffuncname
    - nakedret
    - prealloc
    - interfacer
    - structcheck
    - varcheck
    - scopelint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - dupl
        - lll
        - goconst

    - path: examples/
      linters:
        - lll
        - gomnd

    - path: cmd/
      linters:
        - gochecknoinits
        - funlen
        - gocognit
        - gocyclo

    - text: "weak cryptographic primitive"
      linters:
        - gosec

    - text: "Use of unsafe calls should be audited"
      linters:
        - gosec

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false